### ISSUE TITLE
ValueError: shape mismatch in Leshy._add_shadows_get_imps during feature importance computation

### ISSUE THREAD

**Issue by guo120** [ThomasBury/arfs#49] opened 2024-09-26 09:20 UTC
Hello,

I encountered a ValueError while using the Leshy feature selector from the arfs package to compute feature importance for several models. The issue occurs during the _add_shadows_get_imps method, where there is a shape mismatch between the importance values and the array being assigned. The importance values array has a shape of (10, 2), but it is trying to assign it to an array of shape (10,).

Here is the full error trace:
Traceback (most recent call last):
    ...
    imp_real[x_cur_ind] = imp[:x_cur_w]
ValueError: shape mismatch: value array of shape (10,2) could not be broadcast to indexing result of shape (10,)

Code to Reproduce:
models = [
    RandomForestClassifier(n_jobs=4, oob_score=True),
    CatBoostClassifier(random_state=42, verbose=0),
    LGBMClassifier(random_state=42, verbose=-1),
    LightForestClassifier(n_feat=X.shape[1]),
    XGBClassifier(random_state=42, verbosity=0, eval_metric="logloss"),
]

feat_selector = arfsgroot.Leshy(
    model, n_estimators=100, verbose=1, max_iter=10, random_state=42
)

if __name__ == "__main__":
    # classification
    titanic = load_data(name="Titanic")
    X, y = titanic.data, titanic.target.cat.codes
    cat_f = titanic.categorical
    # running the ARFS methods using different models
    compare_varimp(feat_selector, models, X, y, sample_weight=None)

**Comment by ThomasBury** [comment] 2024-09-27 21:02
Hey @guo120 , thank you for reporting the bug.
The issue was caused by the newer Shap version(s) now outputting a NumPy array instead of a list. This was not detected in the if condition.

fixed by https://github.com/ThomasBury/arfs/commit/95a42cd88179bb2c4b1bbac2a1b2d8f12be663e0 and https://github.com/ThomasBury/arfs/commit/f8f90dabe2871e579dbbdcb8b93fd2dc349d92f8

Update to the new ARFS version 2.3.2 and run the tutorial notebooks. Note that fasttreeshap might not work correctly; any errors encountered should be reported to the fasttreeshap maintainer. Everything else should run without issues.

**Closed by ThomasBury** 2024-09-27 21:02 UTC
Labels: bug
